/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/templates/{code}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_DOCUMENT_GENERATION__DOCUMENT_GENERATION_UI
     */
    put: operations['createOrReplaceTemplate']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    Variable: {
      code: string
      required: boolean
    }
    Group: {
      code: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  createOrReplaceTemplate: {
    parameters: {
      query?: never
      header?: never
      path: {
        code: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'multipart/form-data': {
          name: string
          description?: string
          /** Format: binary */
          file?: string
          templateVariables?: components['schemas']['Variable'][]
          templateGroups?: components['schemas']['Group'][]
        }
      }
    }
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
}
