/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/templates': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /**
     * @description Requires one of the following roles:
     *     * ROLE_DOCUMENT_GENERATION__DOCUMENT_GENERATION_UI
     */
    put: operations['createOrReplaceTemplate']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/variables': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * @description Requires one of the following roles:
     *     * ROLE_DOCUMENT_GENERATION__DOCUMENT_GENERATION_UI
     */
    get: operations['getTemplateVariables']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    Group: {
      code: string
    }
    TemplateRequest: {
      /** Format: uuid */
      id?: string
      code: string
      name: string
      description?: string
      variables: components['schemas']['Variable'][]
      groups: components['schemas']['Group'][]
    }
    Variable: {
      code: string
      required: boolean
      description?: string
    }
    TemplateResponse: {
      /** Format: uuid */
      id: string
    }
    Domain: {
      code: string
      description: string
      variables: components['schemas']['Variable'][]
    }
    TemplateVariables: {
      domains: components['schemas']['Domain'][]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  createOrReplaceTemplate: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'multipart/form-data': {
          template: components['schemas']['TemplateRequest']
          /** Format: binary */
          file?: string
        }
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['TemplateResponse']
        }
      }
    }
  }
  getTemplateVariables: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TemplateVariables']
        }
      }
    }
  }
}
